title: Matt Poland # your name (or website title) here
logo: "/images/ProfilePicture.jpg?raw=true"  # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist, Physician Assistant
  <br><br>
 + <a href="https://www.linkedin.com/in/polandmatt/">My LinkedIn Profile</a><br>
 + <a href="https://gist.github.com/mattpolands/">My GitHub Gists</a><br>  
 + <a href="https://www.datacamp.com/portfolio/matthewdpoland/">My datacamp Profile</a><br>
  








plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

