title: Matt Poland  
logo: "/images/ProfilePicture.jpg?raw=true"  
description: Data Scientist, Physician Assistant  
  <br><br>
 + <a href="https://www.linkedin.com/in/polandmatt/">My LinkedIn Profile</a><br>
 + <a href="https://gist.github.com/mattpolands/">My GitHub Gists</a><br>  
 + <a href="https://www.datacamp.com/portfolio/matthewdpoland/">My datacamp Profile</a><br>
  








plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

