title: Matt Poland  
logo: "/images/CroppedProfilePicture.jpg?raw=true"  
description: Data Scientist and Physician Assistant<br>
 + <a href="https://www.linkedin.com/in/polandmatt/">My LinkedIn Profile</a><br>
 + <a href="https://gist.github.com/mattpolands/">My GitHub Gists</a><br>  
 + <a href="https://www.datacamp.com/portfolio/matthewdpoland/">My datacamp Profile</a><br>
  







remote_theme: pages-themes/minimal@v0.2.0


plugins:
- jekyll-remote-theme


